package dev.sebastiano.bundel.ui

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006e1e)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFF6eff7d)
val md_theme_light_onPrimaryContainer = Color(0xFF08200a)
val md_theme_light_secondary = Color(0xFF7245b5)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFeedcff)
val md_theme_light_onSecondaryContainer = Color(0xFF270057)
val md_theme_light_tertiary = Color(0xFF006e26)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFF8ffa9b)
val md_theme_light_onTertiaryContainer = Color(0xFF002106)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfdf6)
val md_theme_light_onBackground = Color(0xFF1a1c19)
val md_theme_light_surface = Color(0xFFfcfdf6)
val md_theme_light_onSurface = Color(0xFF1a1c19)
val md_theme_light_surfaceVariant = Color(0xFFdee4d9)
val md_theme_light_onSurfaceVariant = Color(0xFF424840)
val md_theme_light_outline = Color(0xFF72796f)
val md_theme_light_inverseOnSurface = Color(0xFFf0f1eb)
val md_theme_light_inverseSurface = Color(0xFF2e312d)

val md_theme_dark_primary = Color(0xFF4de163)
val md_theme_dark_onPrimary = Color(0xFF00390a)
val md_theme_dark_primaryContainer = Color(0xFF005314)
val md_theme_dark_onPrimaryContainer = Color(0xFF6eff7d)
val md_theme_dark_secondary = Color(0xFFd8baff)
val md_theme_dark_onSecondary = Color(0xFF420784)
val md_theme_dark_secondaryContainer = Color(0xFF5a2b9c)
val md_theme_dark_onSecondaryContainer = Color(0xFFeedcff)
val md_theme_dark_tertiary = Color(0xFF73dc81)
val md_theme_dark_onTertiary = Color(0xFF00390f)
val md_theme_dark_tertiaryContainer = Color(0xFF00531b)
val md_theme_dark_onTertiaryContainer = Color(0xFF8ffa9b)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c19)
val md_theme_dark_onBackground = Color(0xFFe2e3dd)
val md_theme_dark_surface = Color(0xFF1a1c19)
val md_theme_dark_onSurface = Color(0xFFe2e3dd)
val md_theme_dark_surfaceVariant = Color(0xFF424840)
val md_theme_dark_onSurfaceVariant = Color(0xFFc2c9bd)
val md_theme_dark_outline = Color(0xFF8c9388)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c19)
val md_theme_dark_inverseSurface = Color(0xFFe2e3dd)

val seed = Color(0xFF4ce062)
val error = Color(0xFFba1b1b)
val Custom0 = Color(0xFF3b64eb)